export const PAGE_HOME = "PAGE_HOME";
export const PAGE_ABOUT = "PAGE_ABOUT";
export const PAGE_SKILLS = "PAGE_SKILLS";
export const PAGE_EXPERIENCE = "PAGE_EXPERIENCE";
export const PAGE_CONTACT = "PAGE_CONTACT";

export const MODAL_CLOSE_TIME = 600;
export const MODAL_HEADER_MENU = "MODAL_HEADER_MENU";
export const MODAL_EXPERIENCE = "MODAL_EXPERIENCE";
